[language-server.rust-analyzer]
environment = { "CARGO_TARGET_DIR" = "target-analyzer" }

[language-server.rust-analyzer.config]
checkOnSave = "true"
check.command = "clippy"
imports.granularity.enforce = "true"
imports.granularity.group = "true"
imports.prefix = "crate"
#rustfmt.extraArgs = ["+nightly-2025-03-18"]

